import { Round, Week } from './types';

export const INITIAL_DATA: Round[] = [
  {
    id: 'first',
    name: 'الدور الأول',
    daysLeft: 50,
    plan: `خطة الدور الأول (50 يوم):
- التركيز المكثف على الأحياء، الإنجليزي، الإسلامية، والفيزياء.
- مراجعة شاملة لكل فصل فور إكماله.
- حل الأسئلة الوزارية للسنوات العشر الأخيرة.`,
    subjects: [
      {
        id: 'bio',
        name: 'أحياء',
        emoji: '🧬',
        topics: [
          // الفصل الأول: الخلية
          { id: 'bio-1-1', chapter: 'الفصل الأول: الخلية', name: 'مقدمة ونظرية الخلية', status: 'not-started' },
          { id: 'bio-1-2', chapter: 'الفصل الأول: الخلية', name: 'حجم الخلية', status: 'not-started' },
          { id: 'bio-1-3', chapter: 'الفصل الأول: الخلية', name: 'الخلية بدائية النواة', status: 'not-started' },
          { id: 'bio-1-4', chapter: 'الفصل الأول: الخلية', name: 'الخلية حقيقية النواة', status: 'not-started' },
          { id: 'bio-1-5', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: الشبكة البلازمية الداخلية', status: 'not-started' },
          { id: 'bio-1-6', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: جهاز كولجي', status: 'not-started' },
          { id: 'bio-1-7', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: المايتوكوندريا', status: 'not-started' },
          { id: 'bio-1-8', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: البلاستيدات', status: 'not-started' },
          { id: 'bio-1-9', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: الجسيمات الحالة', status: 'not-started' },
          { id: 'bio-1-10', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: هيكل الخلية', status: 'not-started' },
          { id: 'bio-1-11', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: الجسيم الحركي', status: 'not-started' },
          { id: 'bio-1-12', chapter: 'الفصل الأول: الخلية', name: 'العضيات الحية: الفجوات', status: 'not-started' },
          { id: 'bio-1-13', chapter: 'الفصل الأول: الخلية', name: 'المحتويات الغير حية: النواة', status: 'not-started' },
          { id: 'bio-1-14', chapter: 'الفصل الأول: الخلية', name: 'الأنشطة الخلوية: الانتشار والنفوذية والتناضح', status: 'not-started' },
          { id: 'bio-1-15', chapter: 'الفصل الأول: الخلية', name: 'الأنشطة الخلوية: النقل النشط والبلعمة والشرب الخلوي والإخراج الخلوي', status: 'not-started' },
          { id: 'bio-1-16', chapter: 'الفصل الأول: الخلية', name: 'الأيض الخلوي: التنفس الخلوي', status: 'not-started' },
          { id: 'bio-1-17', chapter: 'الفصل الأول: الخلية', name: 'الأيض الخلوي: عمليات البناء', status: 'not-started' },
          { id: 'bio-1-18', chapter: 'الفصل الأول: الخلية', name: 'انقسام الخلية: الانقسام المباشر اللاخيطي', status: 'not-started' },
          { id: 'bio-1-19', chapter: 'الفصل الأول: الخلية', name: 'انقسام الخلية: الانقسام غير المباشر الخيطي', status: 'not-started' },
          { id: 'bio-1-20', chapter: 'الفصل الأول: الخلية', name: 'انقسام الخلية: الانقسام الاختزالي الأول', status: 'not-started' },
          { id: 'bio-1-21', chapter: 'الفصل الأول: الخلية', name: 'انقسام الخلية: الانقسام الاختزالي الثاني', status: 'not-started' },
          { id: 'bio-1-22', chapter: 'الفصل الأول: الخلية', name: 'رسم: خلية بدائية النواة (البكتريا)', status: 'not-started' },
          { id: 'bio-1-23', chapter: 'الفصل الأول: الخلية', name: 'رسم: الخلية النباتية', status: 'not-started' },
          { id: 'bio-1-24', chapter: 'الفصل الأول: الخلية', name: 'رسم: الخلية الحيوانية', status: 'not-started' },
          { id: 'bio-1-25', chapter: 'الفصل الأول: الخلية', name: 'رسم: تركيب الغشاء البلازمي', status: 'not-started' },
          { id: 'bio-1-26', chapter: 'الفصل الأول: الخلية', name: 'رسم: تركيب المايتوكوندريا', status: 'not-started' },
          { id: 'bio-1-27', chapter: 'الفصل الأول: الخلية', name: 'رسم: تركيب البلاستيدة الخضراء', status: 'not-started' },
          { id: 'bio-1-28', chapter: 'الفصل الأول: الخلية', name: 'رسم: الكروموسوم', status: 'not-started' },
          { id: 'bio-1-29', chapter: 'الفصل الأول: الخلية', name: 'رسم: عملية الانتشار', status: 'not-started' },
          { id: 'bio-1-30', chapter: 'الفصل الأول: الخلية', name: 'رسم: عملية التناضح في الخلايا الحيوانية والنباتية', status: 'not-started' },
          { id: 'bio-1-31', chapter: 'الفصل الأول: الخلية', name: 'رسم: أطوار الانقسام الخيطي', status: 'not-started' },
          { id: 'bio-1-32', chapter: 'الفصل الأول: الخلية', name: 'رسم: أطوار الانقسام الاختزالي', status: 'not-started' },
          { id: 'bio-1-33', chapter: 'الفصل الأول: الخلية', name: 'أسئلة الفصل الأول', status: 'not-started' },

          // الفصل الثاني: الأنسجة
          { id: 'bio-2-1', chapter: 'الفصل الثاني: الأنسجة', name: 'مقدمة', status: 'not-started' },
          { id: 'bio-2-2', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة النباتية: النسيج المرستيمي', status: 'not-started' },
          { id: 'bio-2-3', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة النباتية: النسيج الأساس (برنكيمي، كولنكيمي، سكلرنكيمي)', status: 'not-started' },
          { id: 'bio-2-4', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة النباتية: نسيج البشرة', status: 'not-started' },
          { id: 'bio-2-5', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة النباتية: النسيج الوعائي (خشب ولحاء)', status: 'not-started' },
          { id: 'bio-2-6', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الظهاري البسيط (حرشفي، مكعبي، عمودي، عمودي مطبق كاذب)', status: 'not-started' },
          { id: 'bio-2-7', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الظهاري المطبق (حرشفي، مكعبي، عمودي، متحول)', status: 'not-started' },
          { id: 'bio-2-8', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام — مكوناته (خلايا وألياف ومادة بين خلوية)', status: 'not-started' },
          { id: 'bio-2-9', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام الأصيل الرخو (هللي، شحمي، متوسط، شبكي، مخاطاني)', status: 'not-started' },
          { id: 'bio-2-10', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام الأصيل الكثيف (أبيض وأصفر)', status: 'not-started' },
          { id: 'bio-2-11', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام الخاص — الغضروف', status: 'not-started' },
          { id: 'bio-2-12', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام الخاص — العظم (مصمت وإسفنجي)', status: 'not-started' },
          { id: 'bio-2-13', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام الخاص — الدم (خلايا حمر، بيض، صفائح دموية، بلازما)', status: 'not-started' },
          { id: 'bio-2-14', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج الضام الخاص — اللمف', status: 'not-started' },
          { id: 'bio-2-15', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج العضلي (ملساء، هيكلية، قلبية)', status: 'not-started' },
          { id: 'bio-2-16', chapter: 'الفصل الثاني: الأنسجة', name: 'الأنسجة الحيوانية: النسيج العصبي', status: 'not-started' },
          { id: 'bio-2-17', chapter: 'الفصل الثاني: الأنسجة', name: 'رسم: نسيج اللحاء', status: 'not-started' },
          { id: 'bio-2-18', chapter: 'الفصل الثاني: الأنسجة', name: 'رسم: الأنسجة الظهارية البسيطة والمطبقة', status: 'not-started' },
          { id: 'bio-2-19', chapter: 'الفصل الثاني: الأنسجة', name: 'رسم: النسيج الضام المغراوي الكثيف المنتظم', status: 'not-started' },
          { id: 'bio-2-20', chapter: 'الفصل الثاني: الأنسجة', name: 'رسم: العظم المصمت', status: 'not-started' },
          { id: 'bio-2-21', chapter: 'الفصل الثاني: الأنسجة', name: 'رسم: خلايا الدم في الإنسان', status: 'not-started' },
          { id: 'bio-2-22', chapter: 'الفصل الثاني: الأنسجة', name: 'رسم: أنواع العضلات', status: 'not-started' },
          { id: 'bio-2-23', chapter: 'الفصل الثاني: الأنسجة', name: 'أسئلة الفصل الثاني', status: 'not-started' },

          // الفصل الثالث: التكاثر
          { id: 'bio-3-1', chapter: 'الفصل الثالث: التكاثر', name: 'مقدمة ومفهوم التكاثر', status: 'not-started' },
          { id: 'bio-3-2', chapter: 'الفصل الثالث: التكاثر', name: 'أنواع التكاثر: اللاجنسي', status: 'not-started' },
          { id: 'bio-3-3', chapter: 'الفصل الثالث: التكاثر', name: 'أنواع التكاثر: الجنسي (تكوين النطف وتكوين البيوض)', status: 'not-started' },
          { id: 'bio-3-4', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الفيروسات (البلعم البكتيري)', status: 'not-started' },
          { id: 'bio-3-5', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في البدائيات: البكتريا (انشطار ثنائي واقتران)', status: 'not-started' },
          { id: 'bio-3-6', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في البدائيات: الطحالب الخضر المزرقة', status: 'not-started' },
          { id: 'bio-3-7', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الطليعيات: الكلاميدوموناس (لا جنسي وجنسي)', status: 'not-started' },
          { id: 'bio-3-8', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الطليعيات: البراميسيوم (لا جنسي وجنسي — اقتران واخصاب ذاتي)', status: 'not-started' },
          { id: 'bio-3-9', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الطليعيات: اليوغلينا (انقسام اختزالي طولي)', status: 'not-started' },
          { id: 'bio-3-10', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الفطريات (لا جنسي وجنسي)', status: 'not-started' },
          { id: 'bio-3-11', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في النباتات: الحزازيات (طور بوغي ومشيجي)', status: 'not-started' },
          { id: 'bio-3-12', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في النباتات: السرخسيات', status: 'not-started' },
          { id: 'bio-3-13', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في النباتات الزهرية: تكوين حبوب اللقاح والبويضات', status: 'not-started' },
          { id: 'bio-3-14', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في النباتات الزهرية: التلقيح وتكوين أنبوب اللقاح والاخصاب', status: 'not-started' },
          { id: 'bio-3-15', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في النباتات الزهرية: تكوين البذرة وتكوين الثمرة', status: 'not-started' },
          { id: 'bio-3-16', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الحشرات (الاخصاب)', status: 'not-started' },
          { id: 'bio-3-17', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في البرمائيات (التزاوج والاخصاب)', status: 'not-started' },
          { id: 'bio-3-18', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الإنسان: الجهاز التناسلي الذكري وتكوين النطف', status: 'not-started' },
          { id: 'bio-3-19', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الإنسان: الجهاز التناسلي الأنثوي', status: 'not-started' },
          { id: 'bio-3-20', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر في الإنسان: الاخصاب والحمل', status: 'not-started' },
          { id: 'bio-3-21', chapter: 'الفصل الثالث: التكاثر', name: 'الدورة الحيضية', status: 'not-started' },
          { id: 'bio-3-22', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر العذري', status: 'not-started' },
          { id: 'bio-3-23', chapter: 'الفصل الثالث: التكاثر', name: 'التكاثر الخنثي', status: 'not-started' },
          { id: 'bio-3-24', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: تكوين النطف في الثدييات', status: 'not-started' },
          { id: 'bio-3-25', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: تكوين البيوض في الثدييات', status: 'not-started' },
          { id: 'bio-3-26', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: التكاثر في الفيروسات', status: 'not-started' },
          { id: 'bio-3-27', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: الانشطار الثنائي في البكتيريا', status: 'not-started' },
          { id: 'bio-3-28', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: الاقتران البكتيري', status: 'not-started' },
          { id: 'bio-3-29', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: الانقسام الثنائي في البراميسيوم', status: 'not-started' },
          { id: 'bio-3-30', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: الاقتران في البراميسيوم', status: 'not-started' },
          { id: 'bio-3-31', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: الانقسام الطولي في اليوغلينا', status: 'not-started' },
          { id: 'bio-3-32', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: تعاقب الأجيال في النبات', status: 'not-started' },
          { id: 'bio-3-33', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: تركيب الزهرة', status: 'not-started' },
          { id: 'bio-3-34', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: التكوين الجنيني لنبات من ذوات الفلقتين', status: 'not-started' },
          { id: 'bio-3-35', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: تركيب البذور (ذوات فلقة وذوات فلقتين)', status: 'not-started' },
          { id: 'bio-3-36', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: تركيب الثمرة', status: 'not-started' },
          { id: 'bio-3-37', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: جهاز التكاثر في الحشرات (ذكري وأنثوي)', status: 'not-started' },
          { id: 'bio-3-38', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: الجهاز التناسلي الذكري في الإنسان', status: 'not-started' },
          { id: 'bio-3-39', chapter: 'الفصل الثالث: التكاثر', name: 'رسم: أحداث الدورة المبيضية', status: 'not-started' },
          { id: 'bio-3-40', chapter: 'الفصل الثالث: التكاثر', name: 'أسئلة الفصل الثالث', status: 'not-started' },

          // الفصل الرابع: التكوين الجنيني
          { id: 'bio-4-1', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'مقدمة ومفهوم النمو', status: 'not-started' },
          { id: 'bio-4-2', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'مفهوم التمايز الخلوي', status: 'not-started' },
          { id: 'bio-4-3', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'مستويات التعضي في تعقيد الحيوان', status: 'not-started' },
          { id: 'bio-4-4', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'مفهوم التكوين الجنيني', status: 'not-started' },
          { id: 'bio-4-5', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'نظريات التكوين الجنيني', status: 'not-started' },
          { id: 'bio-4-6', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'مفاهيم التكوين الجنيني الأساسية', status: 'not-started' },
          { id: 'bio-4-7', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'التشوهات الخلقية في الإنسان', status: 'not-started' },
          { id: 'bio-4-8', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'التوائم', status: 'not-started' },
          { id: 'bio-4-9', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'المباعدة بين الولادات', status: 'not-started' },
          { id: 'bio-4-10', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'الخلايا الجذعية', status: 'not-started' },
          { id: 'bio-4-11', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'الاستنساخ في الحيوان', status: 'not-started' },
          { id: 'bio-4-12', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'علاج العقم', status: 'not-started' },
          { id: 'bio-4-13', chapter: 'الفصل الرابع: التكوين الجنيني', name: 'أسئلة الفصل الرابع', status: 'not-started' },

          // الفصل الخامس: الوراثة
          { id: 'bio-5-1', chapter: 'الفصل الخامس: الوراثة', name: 'مقدمة', status: 'not-started' },
          { id: 'bio-5-2', chapter: 'الفصل الخامس: الوراثة', name: 'الوراثة ما قبل مندل', status: 'not-started' },
          { id: 'bio-5-3', chapter: 'الفصل الخامس: الوراثة', name: 'الوراثة المندلية', status: 'not-started' },
          { id: 'bio-5-4', chapter: 'الفصل الخامس: الوراثة', name: 'نموذج الطريقة التجريبية لدراسة طرز التوارث', status: 'not-started' },
          { id: 'bio-5-5', chapter: 'الفصل الخامس: الوراثة', name: 'المصطلحات والرموز الوراثية', status: 'not-started' },
          { id: 'bio-5-6', chapter: 'الفصل الخامس: الوراثة', name: 'التهجين الأحادي', status: 'not-started' },
          { id: 'bio-5-7', chapter: 'الفصل الخامس: الوراثة', name: 'التهجين العكسي', status: 'not-started' },
          { id: 'bio-5-8', chapter: 'الفصل الخامس: الوراثة', name: 'فرضيات مندل', status: 'not-started' },
          { id: 'bio-5-9', chapter: 'الفصل الخامس: الوراثة', name: 'مربع بوينت', status: 'not-started' },
          { id: 'bio-5-10', chapter: 'الفصل الخامس: الوراثة', name: 'التضريب الاختباري', status: 'not-started' },
          { id: 'bio-5-11', chapter: 'الفصل الخامس: الوراثة', name: 'التضريب الرجعي', status: 'not-started' },
          { id: 'bio-5-12', chapter: 'الفصل الخامس: الوراثة', name: 'التهجين الثنائي وقانون التوزيع الحر', status: 'not-started' },
          { id: 'bio-5-13', chapter: 'الفصل الخامس: الوراثة', name: 'التضريب الاختباري لصفتين', status: 'not-started' },
          { id: 'bio-5-14', chapter: 'الفصل الخامس: الوراثة', name: 'تفسير نتائج مندل (الكروموسوم)', status: 'not-started' },
          { id: 'bio-5-15', chapter: 'الفصل الخامس: الوراثة', name: 'الاحتمالات الوراثية في تجارب مندل', status: 'not-started' },
          { id: 'bio-5-16', chapter: 'الفصل الخامس: الوراثة', name: 'الوراثة ما بعد مندل', status: 'not-started' },
          { id: 'bio-5-17', chapter: 'الفصل الخامس: الوراثة', name: 'الصفات التي تتحور عن النسبة المندلية 3:1', status: 'not-started' },
          { id: 'bio-5-18', chapter: 'الفصل الخامس: الوراثة', name: 'النفاذ الجيني', status: 'not-started' },
          { id: 'bio-5-19', chapter: 'الفصل الخامس: الوراثة', name: 'الوراثة والبيئة', status: 'not-started' },
          { id: 'bio-5-20', chapter: 'الفصل الخامس: الوراثة', name: 'تداخل الفعل الجيني', status: 'not-started' },
          { id: 'bio-5-21', chapter: 'الفصل الخامس: الوراثة', name: 'الآليات المتعددة', status: 'not-started' },
          { id: 'bio-5-22', chapter: 'الفصل الخامس: الوراثة', name: 'نظام ABO', status: 'not-started' },
          { id: 'bio-5-23', chapter: 'الفصل الخامس: الوراثة', name: 'نقل الدم', status: 'not-started' },
          { id: 'bio-5-24', chapter: 'الفصل الخامس: الوراثة', name: 'مستضدات العامل الرئيسي', status: 'not-started' },
          { id: 'bio-5-25', chapter: 'الفصل الخامس: الوراثة', name: 'وراثة نظام الـ RH', status: 'not-started' },
          { id: 'bio-5-26', chapter: 'الفصل الخامس: الوراثة', name: 'الطفرات الكروموسومية (تغيرات في عدد وتركيب الكروموسوم)', status: 'not-started' },
          { id: 'bio-5-27', chapter: 'الفصل الخامس: الوراثة', name: 'الطفرات الجينية (النقطية والمضاعفة)', status: 'not-started' },
          { id: 'bio-5-28', chapter: 'الفصل الخامس: الوراثة', name: 'الوراثة البشرية', status: 'not-started' },
          { id: 'bio-5-29', chapter: 'الفصل الخامس: الوراثة', name: 'سجلات النسب', status: 'not-started' },
          { id: 'bio-5-30', chapter: 'الفصل الخامس: الوراثة', name: 'توارث الصفات في الإنسان', status: 'not-started' },
          { id: 'bio-5-31', chapter: 'الفصل الخامس: الوراثة', name: 'كروموسومات الإنسان', status: 'not-started' },
          { id: 'bio-5-32', chapter: 'الفصل الخامس: الوراثة', name: 'تشخيص الأمراض الوراثية وتخفيف أعراضها', status: 'not-started' },
          { id: 'bio-5-33', chapter: 'الفصل الخامس: الوراثة', name: 'الاستشارات الوراثية', status: 'not-started' },
          { id: 'bio-5-34', chapter: 'الفصل الخامس: الوراثة', name: 'الجينوم البشري', status: 'not-started' },
          { id: 'bio-5-35', chapter: 'الفصل الخامس: الوراثة', name: 'الأساس الجزيئي للوراثة', status: 'not-started' },
          { id: 'bio-5-36', chapter: 'الفصل الخامس: الوراثة', name: 'الكشف عن الحامض النووي', status: 'not-started' },
          { id: 'bio-5-37', chapter: 'الفصل الخامس: الوراثة', name: 'تركيب الـ DNA', status: 'not-started' },
          { id: 'bio-5-38', chapter: 'الفصل الخامس: الوراثة', name: 'تركيب الـ RNA', status: 'not-started' },
          { id: 'bio-5-39', chapter: 'الفصل الخامس: الوراثة', name: 'الحامض DNA وقابليته على نسخ الـ RNA', status: 'not-started' },
          { id: 'bio-5-40', chapter: 'الفصل الخامس: الوراثة', name: 'ترجمة الـ DNA لبناء البروتين', status: 'not-started' },
          { id: 'bio-5-41', chapter: 'الفصل الخامس: الوراثة', name: 'الهندسة الوراثية', status: 'not-started' },
          { id: 'bio-5-42', chapter: 'الفصل الخامس: الوراثة', name: 'التطبيقات الوراثية', status: 'not-started' },
          { id: 'bio-5-43', chapter: 'الفصل الخامس: الوراثة', name: 'أسئلة الفصل الخامس', status: 'not-started' },
        ],
      },
      {
        id: 'eng',
        name: 'إنجليزي',
        emoji: '🇬🇧',
        topics: [
          // Unit 1
          { id: 'eng-1-1', chapter: 'Unit One', name: 'my toe is bleeding (verbs, nouns, adjectives)', status: 'not-started' },
          { id: 'eng-1-2', chapter: 'Unit One', name: 'I was ice skating (past simple & continuous)', status: 'not-started' },
          { id: 'eng-1-3', chapter: 'Unit One', name: 'Phrasal verbs: up / down / off & prefixes (un, in...)', status: 'not-started' },
          { id: 'eng-1-4', chapter: 'Unit One', name: 'Used to and comparative adjectives', status: 'not-started' },
          { id: 'eng-1-5', chapter: 'Unit One', name: 'Revision & Test (Unit 1)', status: 'not-started' },
          { id: 'eng-1-6', chapter: 'Unit One', name: 'Writing: cigarette advertising / car accidents', status: 'not-started' },
          
          // Unit 2
          { id: 'eng-2-1', chapter: 'Unit Two', name: 'Law and order (used to revision)', status: 'not-started' },
          { id: 'eng-2-2', chapter: 'Unit Two', name: 'Police officers duties (Must, Have to, need to)', status: 'not-started' },
          { id: 'eng-2-3', chapter: 'Unit Two', name: 'Airport Security (polite requests, suggestions, offers)', status: 'not-started' },
          { id: 'eng-2-4', chapter: 'Unit Two', name: 'Military Jobs (should / shouldn\'t)', status: 'not-started' },
          { id: 'eng-2-5', chapter: 'Unit Two', name: 'A robbery (Have, get, make informal passive)', status: 'not-started' },
          { id: 'eng-2-6', chapter: 'Unit Two', name: 'Road safety & Security technology', status: 'not-started' },
          { id: 'eng-2-7', chapter: 'Unit Two', name: 'Writing: Road safety / Advice on interview', status: 'not-started' },
          
          // Unit 3
          { id: 'eng-3-1', chapter: 'Unit Three', name: 'Tourist industry (Phrases for writing definitions)', status: 'not-started' },
          { id: 'eng-3-2', chapter: 'Unit Three', name: 'Conditionals (Zero, First, Second, Third)', status: 'not-started' },
          { id: 'eng-3-3', chapter: 'Unit Three', name: 'Regret (I wish and If only)', status: 'not-started' },
          { id: 'eng-3-4', chapter: 'Unit Three', name: 'Summer jobs & Focus on careers', status: 'not-started' },
          { id: 'eng-3-5', chapter: 'Unit Three', name: 'Writing: advantages of studying English / ask friend', status: 'not-started' },
          
          // Unit 4
          { id: 'eng-4-1', chapter: 'Unit Four', name: 'Rashid & Rana Designs (past simple & continuous)', status: 'not-started' },
          { id: 'eng-4-2', chapter: 'Unit Four', name: 'Used to (People didn\'t use to work out at home)', status: 'not-started' },
          { id: 'eng-4-3', chapter: 'Unit Four', name: 'Writing: a company you have recently set up', status: 'not-started' },

          // Unit 5
          { id: 'eng-5-1', chapter: 'Unit Five', name: 'Sightseeing (Compound nouns)', status: 'not-started' },
          { id: 'eng-5-2', chapter: 'Unit Five', name: 'Present perfect simple & continuous (since/for)', status: 'not-started' },
          { id: 'eng-5-3', chapter: 'Unit Five', name: 'Relative clauses (Defining and non-defining)', status: 'not-started' },
          { id: 'eng-5-4', chapter: 'Unit Five', name: 'Writing: a brief description of the holiday / advice', status: 'not-started' },
          
          // Unit 6
          { id: 'eng-6-1', chapter: 'Unit Six', name: 'Passive voice (Present, Past, Future, Continuous, Perfect)', status: 'not-started' },
          { id: 'eng-6-2', chapter: 'Unit Six', name: 'Meet a banker & car loan (Conditionals)', status: 'not-started' },
          { id: 'eng-6-3', chapter: 'Unit Six', name: 'Writing: A complaint to a Bank', status: 'not-started' },
          
          // Unit 7
          { id: 'eng-7-1', chapter: 'Unit Seven', name: 'Future forms & Future in the past', status: 'not-started' },
          { id: 'eng-7-2', chapter: 'Unit Seven', name: 'Learning experiences & Volunteers', status: 'not-started' },
          { id: 'eng-7-3', chapter: 'Unit Seven', name: 'Writing: studying while you are working', status: 'not-started' },

          // Unit 8
          { id: 'eng-8-1', chapter: 'Unit Eight', name: 'Natural resource (Prefixes/Suffixes) & Recycling waste', status: 'not-started' },
          { id: 'eng-8-2', chapter: 'Unit Eight', name: 'Renewable resource & Careers connected with environment', status: 'not-started' },
          { id: 'eng-8-3', chapter: 'Unit Eight', name: 'Writing: way people can help to improve environment', status: 'not-started' },
          
          // Literature
          { id: 'eng-lit-1', chapter: 'Literature', name: 'Pride and Prejudice (Sections 1-6)', status: 'not-started' },
          { id: 'eng-lit-2', chapter: 'Literature', name: 'As You Like It (Sections 1-6)', status: 'not-started' },
        ],
      },
      {
        id: 'isl',
        name: 'إسلامية',
        emoji: '🕌',
        topics: [
          { id: 'isl-t-1', chapter: 'أحكام التلاوة', name: 'النون الساكنة والتنوين (الإظهار، الإقلاب، الإدغام، الإخفاء)', status: 'not-started' },
          { id: 'isl-t-2', chapter: 'أحكام التلاوة', name: 'تمرينات أحكام التلاوة', status: 'not-started' },
          
          { id: 'isl-1-1', chapter: 'الوحدة الأولى', name: 'سورة البقرة (معاني - شرح الآيات)', status: 'not-started' },
          { id: 'isl-1-2', chapter: 'الوحدة الأولى', name: 'أصحاب الكهف (القصة - أهم ما ترشد إليه)', status: 'not-started' },
          { id: 'isl-1-3', chapter: 'الوحدة الأولى', name: 'التعاون بين المسلمين', status: 'not-started' },
          { id: 'isl-1-4', chapter: 'الوحدة الأولى', name: 'نظام الأسرة في الإسلام', status: 'not-started' },
          { id: 'isl-1-5', chapter: 'الوحدة الأولى', name: 'النهي عن الغضب', status: 'not-started' },
          
          { id: 'isl-2-1', chapter: 'الوحدة الثانية', name: 'سورة آل عمران (معاني - شرح الآيات)', status: 'not-started' },
          { id: 'isl-2-2', chapter: 'الوحدة الثانية', name: 'مريم بنت عمران (القصة - أهم ما ترشد إليه)', status: 'not-started' },
          { id: 'isl-2-3', chapter: 'الوحدة الثانية', name: 'الناجون يوم القيامة', status: 'not-started' },
          { id: 'isl-2-4', chapter: 'الوحدة الثانية', name: 'حقوق الزوجين', status: 'not-started' },
          { id: 'isl-2-5', chapter: 'الوحدة الثانية', name: 'قصص وعبر', status: 'not-started' },
          
          { id: 'isl-3-1', chapter: 'الوحدة الثالثة', name: 'سورة النساء (معاني - شرح الآيات)', status: 'not-started' },
          { id: 'isl-3-2', chapter: 'الوحدة الثالثة', name: 'موسى والعبد الصالح (القصة - أهم ما ترشد إليه)', status: 'not-started' },
          { id: 'isl-3-3', chapter: 'الوحدة الثالثة', name: 'محاسبة النفس', status: 'not-started' },
          { id: 'isl-3-4', chapter: 'الوحدة الثالثة', name: 'نظرة عامة للنظام الاقتصادي', status: 'not-started' },
          { id: 'isl-3-5', chapter: 'الوحدة الثالثة', name: 'الرجولة', status: 'not-started' },
          
          { id: 'isl-4-1', chapter: 'الوحدة الرابعة', name: 'سورة الإسراء (معاني - شرح الآيات)', status: 'not-started' },
          { id: 'isl-4-2', chapter: 'الوحدة الرابعة', name: 'شعيب عليه السلام (القصة - أهم ما ترشد إليه)', status: 'not-started' },
          { id: 'isl-4-3', chapter: 'الوحدة الرابعة', name: 'في الجهاد وكرامة المجاهد', status: 'not-started' },
          { id: 'isl-4-4', chapter: 'الوحدة الرابعة', name: 'الوظائف الاقتصادية', status: 'not-started' },
          { id: 'isl-4-5', chapter: 'الوحدة الرابعة', name: 'التكبر', status: 'not-started' },
          
          { id: 'isl-5-1', chapter: 'الوحدة الخامسة', name: 'سورة الأنبياء (معاني - شرح الآيات)', status: 'not-started' },
          { id: 'isl-5-2', chapter: 'الوحدة الخامسة', name: 'نبأ الفاسق (القصة - أهم ما ترشد إليه)', status: 'not-started' },
          { id: 'isl-5-3', chapter: 'الوحدة الخامسة', name: 'حسن الخلق', status: 'not-started' },
          { id: 'isl-5-4', chapter: 'الوحدة الخامسة', name: 'التسامح والتعايش السلمي', status: 'not-started' },
          { id: 'isl-5-5', chapter: 'الوحدة الخامسة', name: 'القناعة', status: 'not-started' },
        ],
      },
      {
        id: 'phys',
        name: 'فيزياء',
        emoji: '⚡',
        topics: [
          // الفصل الأول: المتسعة
          { id: 'phys-1-1', chapter: 'الفصل الأول: المتسعة', name: 'المتسعة والمتسعة ذات الصفيحتين المتوازيتين', status: 'not-started' },
          { id: 'phys-1-2', chapter: 'الفصل الأول: المتسعة', name: 'السعة والعازل الكهربائي', status: 'not-started' },
          { id: 'phys-1-3', chapter: 'الفصل الأول: المتسعة', name: 'العوامل المؤثرة في مقدار سعة المتسعة', status: 'not-started' },
          { id: 'phys-1-4', chapter: 'الفصل الأول: المتسعة', name: 'ربط المتسعات على التوازي والتوالي', status: 'not-started' },
          { id: 'phys-1-5', chapter: 'الفصل الأول: المتسعة', name: 'الطاقة المختزنة في المجال الكهربائي للمتسعة', status: 'not-started' },
          { id: 'phys-1-6', chapter: 'الفصل الأول: المتسعة', name: 'انواع المتسعات ودائرة تيار مستمر (RC)', status: 'not-started' },
          { id: 'phys-1-7', chapter: 'الفصل الأول: المتسعة', name: 'نشاط: شحن وتفريغ المتسعة', status: 'not-started' },
          { id: 'phys-1-8', chapter: 'الفصل الأول: المتسعة', name: 'تطبيقات عملية وأسئلة ومسائل الفصل الأول', status: 'not-started' },
          
          // الفصل الثاني: الحث الكهرومغناطيسي
          { id: 'phys-2-1', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'مقدمة وتأثير المجالين الكهربائي والمغناطيسي في الجسيمات', status: 'not-started' },
          { id: 'phys-2-2', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'الحث الكهرومغناطيسي واكتشاف فاراداي', status: 'not-started' },
          { id: 'phys-2-3', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'نشاط: توضيح ظاهرة الحث الكهرومغناطيسي', status: 'not-started' },
          { id: 'phys-2-4', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'القوة الدافعة الكهربائية الحركية وحفظ الطاقة', status: 'not-started' },
          { id: 'phys-2-5', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'الفيض المغناطيسي ونشاط تجربة فاراداي', status: 'not-started' },
          { id: 'phys-2-6', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'قانون لنز والتيارات الدوامة (مع النشاط)', status: 'not-started' },
          { id: 'phys-2-7', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'المولدات والمحركات الكهربائية للتيار المستمر', status: 'not-started' },
          { id: 'phys-2-8', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'المحّث والحث الذاتي (مع النشاط) والطاقة المختزنة', status: 'not-started' },
          { id: 'phys-2-9', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'الحث المتبادل والمجالات الكهربائية المحتثة', status: 'not-started' },
          { id: 'phys-2-10', chapter: 'الفصل الثاني: الحث الكهرومغناطيسي', name: 'تطبيقات عملية وأسئلة ومسائل الفصل الثاني', status: 'not-started' },
          
          // الفصل الثالث: التيار المتناوب
          { id: 'phys-3-1', chapter: 'الفصل الثالث: التيار المتناوب', name: 'مقدمة ودوائر التيار المتناوب (مقاومة صرف)', status: 'not-started' },
          { id: 'phys-3-2', chapter: 'الفصل الثالث: التيار المتناوب', name: 'المقدار المؤثر للتيار المتناوب', status: 'not-started' },
          { id: 'phys-3-3', chapter: 'الفصل الثالث: التيار المتناوب', name: 'دائرة تيار متناوب الحمل فيها محث صرف (مع الأنشطة)', status: 'not-started' },
          { id: 'phys-3-4', chapter: 'الفصل الثالث: التيار المتناوب', name: 'دائرة تيار متناوب الحمل فيها متسعة صرف (مع الأنشطة)', status: 'not-started' },
          { id: 'phys-3-5', chapter: 'الفصل الثالث: التيار المتناوب', name: 'دائرة (R-L-C) متوالية الربط وعامل القدرة', status: 'not-started' },
          { id: 'phys-3-6', chapter: 'الفصل الثالث: التيار المتناوب', name: 'الاهتزاز الكهرومغناطيسي والرنين', status: 'not-started' },
          { id: 'phys-3-7', chapter: 'الفصل الثالث: التيار المتناوب', name: 'دائرة (R-L-C) متوازية الربط وعامل النوعية', status: 'not-started' },
          { id: 'phys-3-8', chapter: 'الفصل الثالث: التيار المتناوب', name: 'أسئلة ومسائل الفصل الثالث', status: 'not-started' },

          // الفصل الرابع: الموجات الكهرومغناطيسية
          { id: 'phys-4-1', chapter: 'الفصل الرابع: الموجات الكهرومغناطيسية', name: 'مقدمة وماكسويل وتوليد الموجات', status: 'not-started' },
          { id: 'phys-4-2', chapter: 'الفصل الرابع: الموجات الكهرومغناطيسية', name: 'مبادئ وكيفية عمل دائرة الارسال والتسلم', status: 'not-started' },
          { id: 'phys-4-3', chapter: 'الفصل الرابع: الموجات الكهرومغناطيسية', name: 'الكشف عن الموجات (مجال كهربائي ومغناطيسي)', status: 'not-started' },
          { id: 'phys-4-4', chapter: 'الفصل الرابع: الموجات الكهرومغناطيسية', name: 'التضمين ومدى وانتشار الموجات', status: 'not-started' },
          { id: 'phys-4-5', chapter: 'الفصل الرابع: الموجات الكهرومغناطيسية', name: 'تطبيقات الموجات وأسئلة ومسائل الفصل الرابع', status: 'not-started' },
          
          // الفصل الخامس: البصريات الفيزيائية
          { id: 'phys-5-1', chapter: 'الفصل الخامس: البصريات الفيزيائية', name: 'مقدمة وتداخل الموجات الضوئية (مع النشاط)', status: 'not-started' },
          { id: 'phys-5-2', chapter: 'الفصل الخامس: البصريات الفيزيائية', name: 'تجربة شقي يونك والتداخل في الأغشية الرقيقة', status: 'not-started' },
          { id: 'phys-5-3', chapter: 'الفصل الخامس: البصريات الفيزيائية', name: 'حيود الضوء ومحزز الحيود (مع النشاط)', status: 'not-started' },
          { id: 'phys-5-4', chapter: 'الفصل الخامس: البصريات الفيزيائية', name: 'استقطاب الضوء وطرائقه (مع الأنشطة)', status: 'not-started' },
          { id: 'phys-5-5', chapter: 'الفصل الخامس: البصريات الفيزيائية', name: 'استطارة الضوء وأسئلة ومسائل الفصل الخامس', status: 'not-started' },
          
          // الفصل السادس: الفيزياء الحديثة
          { id: 'phys-6-1', chapter: 'الفصل السادس: الفيزياء الحديثة', name: 'مقدمة ونظرية الكم والظاهرة الكهروضوئية (مع النشاط)', status: 'not-started' },
          { id: 'phys-6-2', chapter: 'الفصل السادس: الفيزياء الحديثة', name: 'الجسيمات والموجات والموجات المادية', status: 'not-started' },
          { id: 'phys-6-3', chapter: 'الفصل السادس: الفيزياء الحديثة', name: 'ميكانيك الكم ودالة الموجة ومبدأ اللادقة', status: 'not-started' },
          { id: 'phys-6-4', chapter: 'الفصل السادس: الفيزياء الحديثة', name: 'النظرية النسبية وفرضيات أينشتاين وتحويلات لورنتز', status: 'not-started' },
          { id: 'phys-6-5', chapter: 'الفصل السادس: الفيزياء الحديثة', name: 'نتائج النسبية وتكافؤ الكتلة والطاقة وأسئلة ومسائل الفصل السادس', status: 'not-started' },
          
          // الفصل السابع: إلكترونيات الحالة الصلبة
          { id: 'phys-7-1', chapter: 'الفصل السابع: إلكترونيات الحالة الصلبة', name: 'مقدمة والمدارات وحزم الطاقة في المواد الصلبة', status: 'not-started' },
          { id: 'phys-7-2', chapter: 'الفصل السابع: إلكترونيات الحالة الصلبة', name: 'أشباه الموصلات النقية والمطعمة (N, P)', status: 'not-started' },
          { id: 'phys-7-3', chapter: 'الفصل السابع: إلكترونيات الحالة الصلبة', name: 'الثنائي PN وفولطية الانحياز وأنواع الثنائيات', status: 'not-started' },
          { id: 'phys-7-4', chapter: 'الفصل السابع: إلكترونيات الحالة الصلبة', name: 'الترانزستور والمضخمات (PNP)', status: 'not-started' },
          { id: 'phys-7-5', chapter: 'الفصل السابع: إلكترونيات الحالة الصلبة', name: 'أسئلة ومسائل الفصل السابع', status: 'not-started' },
          
          // الفصل الثامن: الأطياف الذرية والليزر
          { id: 'phys-8-1', chapter: 'الفصل الثامن: الأطياف الذرية والليزر', name: 'مقدمة وانموذج بور وطيف الهيدروجين والأطياف', status: 'not-started' },
          { id: 'phys-8-2', chapter: 'الفصل الثامن: الأطياف الذرية والليزر', name: 'اطياف الانبعاث والامتصاص ونشاط أنواع الأطياف', status: 'not-started' },
          { id: 'phys-8-3', chapter: 'الفصل الثامن: الأطياف الذرية والليزر', name: 'الأشعة السينية وتأثير كومبتن', status: 'not-started' },
          { id: 'phys-8-4', chapter: 'الفصل الثامن: الأطياف الذرية والليزر', name: 'الليزر والميزر (آلية العمل، الخصائص، المنظومات)', status: 'not-started' },
          { id: 'phys-8-5', chapter: 'الفصل الثامن: الأطياف الذرية والليزر', name: 'أنواع وتطبيقات الليزر وأسئلة ومسائل الفصل الثامن', status: 'not-started' },
          
          // الفصل التاسع: الفيزياء النووية
          { id: 'phys-9-1', chapter: 'الفصل التاسع: الفيزياء النووية', name: 'مقدمة وتركيب النواة وطاقة الربط النووية', status: 'not-started' },
          { id: 'phys-9-2', chapter: 'الفصل التاسع: الفيزياء النووية', name: 'الاحلال الاشعاعي (ألفا، بيتا، كاما)', status: 'not-started' },
          { id: 'phys-9-3', chapter: 'الفصل التاسع: الفيزياء النووية', name: 'التفاعلات النووية والانشطار والاندماج', status: 'not-started' },
          { id: 'phys-9-4', chapter: 'الفصل التاسع: الفيزياء النووية', name: 'مخاطر وفوائد الاشعاع وأسئلة ومسائل الفصل التاسع', status: 'not-started' },
        ],
      },
    ],
  },
];

export const WEEKLY_PLAN: Week[] = [
  {
    id: 1,
    title: 'الأسبوع الأول: انطلاقة قوية',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-1' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-1-1' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-t-1' },
    ],
  },
  {
    id: 2,
    title: 'الأسبوع الثاني: تعميق الفهم',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-2' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-1-2' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-1-1' },
    ],
  },
  {
    id: 3,
    title: 'الأسبوع الثالث: الاستمرارية',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-3' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-1-3' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-2-1' },
      { roundId: 'first', subjectId: 'phys', topicId: 'phys-1-1' },
    ],
  },
  {
    id: 4,
    title: 'الأسبوع الرابع: التركيز العالي',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-4' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-1-4' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-3-1' },
    ],
  },
  {
    id: 5,
    title: 'الأسبوع الخامس: منتصف الطريق',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-5' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-1-5' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-4-1' },
    ],
  },
  {
    id: 6,
    title: 'الأسبوع السادس: الثبات',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-6' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-2-1' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-5-1' },
    ],
  },
  {
    id: 7,
    title: 'الأسبوع السابع: التحدي',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-7' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-2-2' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-t-1' },
      { roundId: 'first', subjectId: 'phys', topicId: 'phys-1-2' },
    ],
  },
  {
    id: 8,
    title: 'الأسبوع الثامن: اللمسات الأخيرة',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-8' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-2-3' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-1-1' },
    ],
  },
  {
    id: 9,
    title: 'الأسبوع التاسع: المراجعة الذهبية',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-9' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-3-2' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-2-1' },
    ],
  },
  {
    id: 10,
    title: 'الأسبوع العاشر: أسبوع الحسم',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-1-10' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-lit-1' },
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-3-1' },
    ],
  },
  {
    id: 11,
    title: 'الأسبوع الحادي عشر: المراجعة المكثفة',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-2-1' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-5-1' },
      { roundId: 'first', subjectId: 'phys', topicId: 'phys-2-1' },
    ],
  },
  {
    id: 12,
    title: 'الأسبوع الثاني عشر: السيطرة التامة',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-2-2' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-6-1' },
    ],
  },
  {
    id: 13,
    title: 'الأسبوع الثالث عشر: قبل الأخير',
    items: [
      { roundId: 'first', subjectId: 'bio', topicId: 'bio-3-1' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-7-1' },
      { roundId: 'first', subjectId: 'phys', topicId: 'phys-3-1' },
    ],
  },
  {
    id: 14,
    title: 'الأسبوع الرابع عشر: أسبوع المراجعة النهائية',
    items: [
      { roundId: 'first', subjectId: 'isl', topicId: 'isl-5-1' },
      { roundId: 'first', subjectId: 'eng', topicId: 'eng-lit-2' },
    ],
  },
];

export const MOTIVATIONAL_MESSAGES = [
  "عاشت إيدك يا بطل! استمر 💪",
  "خطوة بخطوة توصل للقمة 🏔️",
  "فخورين بيك، القادم أفضل 🌟",
  "أنت كدها، لا تتوقف! 🔥",
  "الإنجاز الصغير هو بداية النجاح الكبير ✨",
  "بطل والله، كمل طريقك 🚀",
  "كل موضوع تخلصه يقربك من حلمك 🎓",
  "عاشت الأيادي، أنت مبدع 👏",
];
